#!/usr/bin/env sh
# ─── Config365 — First-run setup script ──────────────────────────────────────
# Run this ONCE before your first `docker compose up --build`.
# Generates a secure random SESSION_SECRET and writes .env.
# If .env already exists, it is left untouched.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../.env"

if [ -f "$ENV_FILE" ]; then
  echo ".env already exists at $ENV_FILE — skipping generation."
  echo "Delete it and re-run if you want to regenerate secrets."
  exit 0
fi

SESSION_SECRET=$(openssl rand -base64 48 | tr -d '\n')

cat > "$ENV_FILE" << EOF
# ─── Config365 — environment variables ──────────────────────────────────────
# Generated by scripts/setup.sh on $(date '+%Y-%m-%d %H:%M:%S').
# Never commit this file to version control.

# ─── Portal ports (host-side) ────────────────────────────────────────────────
# docker compose maps ${PORTAL_HTTP_PORT}:80 — always use compose, not docker run.
PORTAL_HTTP_PORT=8080

# ─── Azure AD ────────────────────────────────────────────────────────────────
# Azure AD credentials are configured through the setup wizard and stored in the
# database. You can override them here for development/emergency use only.
# AZURE_AD_CLIENT_ID=
# AZURE_AD_TENANT_ID=
# AZURE_AD_REDIRECT_URI=http://localhost:8080/auth/callback

# Platform admins (emergency fallback only — first signer becomes admin automatically)
# PLATFORM_ADMIN_OIDS=

# ─── Session ─────────────────────────────────────────────────────────────────
SESSION_SECRET=$SESSION_SECRET

# ─── Gitea ───────────────────────────────────────────────────────────────────
# Gitea token and admin credentials are managed automatically.
# Emergency override only (leave blank in production):
# GITEA_TOKEN=
GITEA_ORG=config365
GITEA_RUNNER_NAME=config365-runner

# ─── M365 automation accounts ────────────────────────────────────────────────
# Collected during the setup wizard and stored in the database.
# M365_CLIENT_ID=
# M365_CLIENT_SECRET=
# M365_MSP_TENANT_ID=
EOF

echo ".env written to $ENV_FILE"
echo ""
echo "Next steps:"
echo "  1. Run: docker compose up -d --build"
echo "  2. Open: http://localhost:8080/setup"
echo "  3. Follow the setup wizard (Gitea connects automatically)"
