#!/usr/bin/env pwsh
# ─── Config365 — First-run setup script ──────────────────────────────────────
# Run this ONCE before your first `docker compose up --build`.
# It generates a secure random SESSION_SECRET and writes a .env file.
# If .env already exists, it is left untouched.

param(
  [string]$EnvFile = (Join-Path $PSScriptRoot ".." ".env")
)

$EnvFile = (Resolve-Path -LiteralPath $EnvFile -ErrorAction SilentlyContinue) ??
           (Join-Path (Split-Path $PSScriptRoot) ".env")

if (Test-Path $EnvFile) {
  Write-Host ".env already exists at $EnvFile — skipping generation." -ForegroundColor Yellow
  Write-Host "Delete it and re-run if you want to regenerate secrets." -ForegroundColor Yellow
  exit 0
}

# Generate cryptographically random secrets
$sessionSecret = [System.Convert]::ToBase64String(
  [System.Security.Cryptography.RandomNumberGenerator]::GetBytes(48)
)

$envContent = @"
# ─── Config365 — environment variables ──────────────────────────────────────
# Generated by scripts/setup.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss').
# Never commit this file to version control.

# ─── Portal ports (host-side) ────────────────────────────────────────────────
# docker compose maps ${PORTAL_HTTP_PORT}:80 — always use compose, not docker run.
PORTAL_HTTP_PORT=8080

# ─── Azure AD ────────────────────────────────────────────────────────────────
# Azure AD credentials are configured through the setup wizard and stored in the
# database. You can override them here for development/emergency use only.
# AZURE_AD_CLIENT_ID=
# AZURE_AD_TENANT_ID=
# AZURE_AD_REDIRECT_URI=http://localhost:8080/auth/callback

# Platform admins (emergency fallback only — first signer becomes admin automatically)
# PLATFORM_ADMIN_OIDS=

# ─── Session ─────────────────────────────────────────────────────────────────
SESSION_SECRET=$sessionSecret

# ─── Gitea ───────────────────────────────────────────────────────────────────
# Gitea token and admin credentials are managed automatically.
# The entrypoint script creates the admin user and writes the portal token
# to a shared Docker volume on first run — no manual steps required.
#
# Emergency override only (leave blank in production):
# GITEA_TOKEN=
GITEA_ORG=config365
GITEA_RUNNER_NAME=config365-runner

# ─── M365 automation accounts ────────────────────────────────────────────────
# Collected during the setup wizard and stored in the database.
# M365_CLIENT_ID=
# M365_CLIENT_SECRET=
# M365_MSP_TENANT_ID=
"@

Set-Content -Path $EnvFile -Value $envContent -Encoding UTF8
Write-Host ".env written to $EnvFile" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Run: docker compose up -d --build" -ForegroundColor White
Write-Host "  2. Open: http://localhost:8080/setup" -ForegroundColor White
Write-Host "  3. Follow the setup wizard (Gitea connects automatically)" -ForegroundColor White
