#!/bin/sh
# setup-runner-shards.sh — provision N act_runner shards and supervisord programs.
#
# Environment:
#   RUNNER_SHARDS          Number of parallel workers (default 4, clamp 1–8)
#   DATA_DIR               Data root (default /data)
#   INIT_DATA              Init state dir (default ${DATA_DIR}/init-data)
#   RUNNER_TOKEN_VAL       Registration token (required when REGISTER=1)
#   GITEA_TOKEN            Portal token injected into runner supervisord env
#   REGISTER               1 = register unregistered shards with Gitea (default 0)
#   RUNNER_LABELS          Label string for act_runner register
#
# Writes:
#   ${INIT_DATA}/runner-shards.txt
#   ${DATA_DIR}/runner-shards/{1..N}/config.yml
#   /etc/supervisord.d/runners.conf

set -e

DATA_DIR="${DATA_DIR:-/data}"
INIT_DATA="${INIT_DATA:-${DATA_DIR}/init-data}"
SHARDS_ROOT="${DATA_DIR}/runner-shards"
SHARDS_FILE="${INIT_DATA}/runner-shards.txt"
SHARD_TEMPLATE="/etc/act_runner/config-shard.yml"
RUNNERS_CONF="/etc/supervisord.d/runners.conf"
RUNNER_LABELS="${RUNNER_LABELS:-self-hosted:host,ubuntu-latest:host,ubuntu-22.04:host,ubuntu-24.04:host}"
REGISTER="${REGISTER:-0}"

# Resolve shard count: env > persisted file > default 4
_shards="${RUNNER_SHARDS:-}"
if [ -z "${_shards}" ] && [ -f "${SHARDS_FILE}" ]; then
  _shards=$(cat "${SHARDS_FILE}" 2>/dev/null | tr -d '\n\r')
fi
if [ -z "${_shards}" ]; then
  _shards=4
fi
# Clamp 1–8
case "${_shards}" in
  ''|*[!0-9]*) _shards=4 ;;
esac
if [ "${_shards}" -lt 1 ]; then _shards=1; fi
if [ "${_shards}" -gt 8 ]; then _shards=8; fi
RUNNER_SHARDS="${_shards}"

mkdir -p "${INIT_DATA}" "${SHARDS_ROOT}" /etc/supervisord.d
printf '%s' "${RUNNER_SHARDS}" > "${SHARDS_FILE}"

# Migrate from legacy single-runner layout
LEGACY_RUNNER="${DATA_DIR}/runner/.runner"
if [ -f "${LEGACY_RUNNER}" ] && [ ! -f "${SHARDS_ROOT}/1/.runner" ]; then
  echo "[runner-shards] Migrating from legacy /data/runner to sharded layout..."
  rm -f "${LEGACY_RUNNER}" "${DATA_DIR}/runner/.runner" 2>/dev/null || true
fi

# Create per-shard config and work dirs
_i=1
while [ "${_i}" -le "${RUNNER_SHARDS}" ]; do
  SHARD_DIR="${SHARDS_ROOT}/${_i}"
  mkdir -p "${SHARD_DIR}/work"
  SHARD_CFG="${SHARD_DIR}/config.yml"
  if [ ! -f "${SHARD_CFG}" ]; then
    sed "s/SHARD_ID/${_i}/g" "${SHARD_TEMPLATE}" > "${SHARD_CFG}"
    echo "[runner-shards] Created config for shard ${_i} at ${SHARD_CFG}"
  fi
  _i=$((_i + 1))
done

# Register shards when requested (Gitea must be reachable)
if [ "${REGISTER}" = "1" ] && [ -n "${RUNNER_TOKEN_VAL:-}" ]; then
  _i=1
  while [ "${_i}" -le "${RUNNER_SHARDS}" ]; do
    SHARD_DIR="${SHARDS_ROOT}/${_i}"
    SHARD_CFG="${SHARD_DIR}/config.yml"
    RUNNER_NAME="config365-runner-${_i}"
    if [ ! -f "${SHARD_DIR}/.runner" ]; then
      echo "[runner-shards] Registering ${RUNNER_NAME}..."
      cd "${SHARD_DIR}"
      act_runner register \
        --no-interactive \
        --instance "http://localhost:3000" \
        --token "${RUNNER_TOKEN_VAL}" \
        --name "${RUNNER_NAME}" \
        --labels "${RUNNER_LABELS}" \
        --config "${SHARD_CFG}"
      echo "[runner-shards] Registered ${RUNNER_NAME}."
    fi
    _i=$((_i + 1))
  done
fi

# Generate supervisord fragment — disable legacy single [program:runner] via comment in main conf
GITEA_TOKEN_ESC="${GITEA_TOKEN:-}"
{
  echo "; Auto-generated by setup-runner-shards.sh — do not edit"
  _i=1
  while [ "${_i}" -le "${RUNNER_SHARDS}" ]; do
    SHARD_DIR="${SHARDS_ROOT}/${_i}"
    SHARD_CFG="${SHARD_DIR}/config.yml"
    cat << EOF

[program:runner-${_i}]
command=/usr/local/bin/runner-start.sh
directory=${SHARD_DIR}
environment=GITEA_INSTANCE_URL="http://localhost:3000",HOME="/root",GIT_TERMINAL_PROMPT="0",PORTAL_TOKEN_API_URL="http://localhost:4322",RUNNER_CONFIG="${SHARD_CFG}",RUNNER_DIR="${SHARD_DIR}"${GITEA_TOKEN_ESC:+,GITEA_TOKEN="${GITEA_TOKEN_ESC}"}
autostart=true
autorestart=true
startretries=5
startsecs=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=30

EOF
    _i=$((_i + 1))
  done
} > "${RUNNERS_CONF}"

echo "[runner-shards] Configured ${RUNNER_SHARDS} parallel worker(s) → ${RUNNERS_CONF}"
